## GRIP MAY'21
## TASK 4 -> Exploratory Data Analysis - Terrorism
Dataset -> https://bit.ly/2TK5Xn5

In [1]:
#impoting required libraries
import pandas as pd

## 1. Reading the Data

In [2]:
df = pd.read_csv("globalterrorismdb_0718dist.csv",encoding='cp1252',low_memory=False)

In [3]:
df.shape

(181691, 135)

In [4]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [5]:
#checking the column names
df.columns.values

array(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region', 'region_txt',
       'provstate', 'city', 'latitude', 'longitude', 'specificity',
       'vicinity', 'location', 'summary', 'crit1', 'crit2', 'crit3',
       'doubtterr', 'alternative', 'alternative_txt', 'multiple',
       'success', 'suicide', 'attacktype1', 'attacktype1_txt',
       'attacktype2', 'attacktype2_txt', 'attacktype3', 'attacktype3_txt',
       'targtype1', 'targtype1_txt', 'targsubtype1', 'targsubtype1_txt',
       'corp1', 'target1', 'natlty1', 'natlty1_txt', 'targtype2',
       'targtype2_txt', 'targsubtype2', 'targsubtype2_txt', 'corp2',
       'target2', 'natlty2', 'natlty2_txt', 'targtype3', 'targtype3_txt',
       'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3', 'natlty3',
       'natlty3_txt', 'gname', 'gsubname', 'gname2', 'gsubname2',
       'gname3', 'gsubname3', 'motive', 'guncertain1', 'guncertain2',
       'guncertain3', 'individual', 'nperps', 'nperpcap', 'claimed',
       'claimmode', 'claimmode_txt', 'claim2', 'claimmode2',
       'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt',
       'compclaim', 'weaptype1', 'weaptype1_txt', 'weapsubtype1',
       'weapsubtype1_txt', 'weaptype2', 'weaptype2_txt', 'weapsubtype2',
       'weapsubtype2_txt', 'weaptype3', 'weaptype3_txt', 'weapsubtype3',
       'weapsubtype3_txt', 'weaptype4', 'weaptype4_txt', 'weapsubtype4',
       'weapsubtype4_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter',
       'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent',
       'propextent_txt', 'propvalue', 'propcomment', 'ishostkid',
       'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'divert',
       'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus',
       'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome',
       'hostkidoutcome_txt', 'nreleased', 'addnotes', 'scite1', 'scite2',
       'scite3', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY',
       'related'], dtype=object)

In [6]:
#changing max column view to 500 so that all columns can be viewed
pd.set_option('display.max_columns', 500)

In [7]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,14,Private Citizens & Property,68.0,Named Civilian,NaN,Julio Guzman,58.0,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANO-D,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,6,Hostage Taking (Kidnapping),NaN,NaN,NaN,NaN,7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",21.0,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd of September Communist League,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN,Mexico,1.0,800000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,1,Assassination,NaN,NaN,NaN,NaN,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Voice of America,Employee,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,1.0,0,NaN,NaN,1,1,1,0.0,NaN,NaN,0.0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Embassy,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,1.0,0,NaN,NaN,1,1,1,-9.0,NaN,NaN,0.0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Consulate,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [8]:
df.isna().sum()

eventid            0
iyear              0
imonth             0
iday               0
approxdate    172452
               ...
INT_LOG            0
INT_IDEO           0
INT_MISC           0
INT_ANY            0
related       156653
Length: 135, dtype: int64

In [9]:
#changing max row display to 400 so that all rows can be viewed
pd.options.display.max_rows = 400

In [10]:
#checking the number of null values in each column
df.isna().sum().sort_values(ascending = False)

gsubname3             181671
weapsubtype4_txt      181621
weapsubtype4          181621
weaptype4             181618
weaptype4_txt         181618
claimmode3            181558
claimmode3_txt        181558
gsubname2             181531
claim3                181373
guncertain3           181371
gname3                181367
divert                181367
attacktype3           181263
attacktype3_txt       181263
ransomnote            181177
ransompaidus          181139
ransomamtus           181128
claimmode2            181075
claimmode2_txt        181075
ransompaid            180917
corp3                 180665
targsubtype3          180594
targsubtype3_txt      180594
natlty3               180544
natlty3_txt           180544
target3               180516
targtype3_txt         180515
targtype3             180515
ransomamt             180341
weapsubtype3          179998
weapsubtype3_txt      179998
weaptype3_txt         179828
weaptype3             179828
claim2                179801
guncertain2           179736
gname2                179678
resolution            179471
kidhijcountry         178386
nhours                177628
compclaim             176852
gsubname              175801
attacktype2           175377
attacktype2_txt       175377
ndays                 173567
approxdate            172452
corp2                 171574
nreleased             171291
targsubtype2_txt      171006
targsubtype2          171006
natlty2_txt           170863
natlty2               170863
hostkidoutcome        170700
hostkidoutcome_txt    170700
target2               170671
targtype2             170547
targtype2_txt         170547
weapsubtype2          170149
weapsubtype2_txt      170149
weaptype2_txt         168564
weaptype2             168564
nhostkidus            168174
nhostkid              168119
claimmode_txt         162608
claimmode             162608
related               156653
addnotes              153402
alternative           152680
alternative_txt       152680
propvalue             142702
scite3                138175
motive                131130
location              126196
propcomment           123732
propextent            117626
propextent_txt        117626
scite2                104758
ransom                104310
nperps                 71115
nperpcap               69489
nwoundte               69143
weapdetail             67670
nkillter               66958
scite1                 66191
summary                66129
claimed                66120
nwoundus               64702
nkillus                64446
corp1                  42550
weapsubtype1_txt       20768
weapsubtype1           20768
nwound                 16311
targsubtype1           10373
targsubtype1_txt       10373
nkill                  10313
longitude               4557
latitude                4556
natlty1                 1559
natlty1_txt             1559
target1                  636
city                     434
provstate                421
guncertain1              380
ishostkid                178
specificity                6
multiple                   1
doubtterr                  1
country_txt                0
region                     0
iday                       0
INT_MISC                   0
INT_IDEO                   0
imonth                     0
extended                   0
iyear                      0
country                    0
vicinity                   0
region_txt                 0
targtype1                  0
crit1                      0
individual                 0
INT_ANY                    0
weaptype1                  0
weaptype1_txt              0
gname                      0
property                   0
targtype1_txt              0
dbsource                   0
crit2                      0
INT_LOG                    0
attacktype1_txt            0
attacktype1                0
suicide                    0
success                    0
crit3                      0
eventid                    0
dtype: int64

## 2. Cleaning the Data

In [11]:
#dropping those columns which have null values greater than 10000
for x in df.columns:
    if df[x].isna().sum()>10000:
        df.drop(x,axis =1,inplace=True)

In [12]:
df.isna().sum().sort_values(ascending = False)

longitude          4557
latitude           4556
natlty1_txt        1559
natlty1            1559
target1             636
city                434
provstate           421
guncertain1         380
ishostkid           178
specificity           6
doubtterr             1
multiple              1
vicinity              0
INT_ANY               0
crit2                 0
region_txt            0
region                0
country_txt           0
country               0
extended              0
iday                  0
imonth                0
iyear                 0
crit1                 0
success               0
crit3                 0
INT_MISC              0
suicide               0
attacktype1           0
attacktype1_txt       0
targtype1             0
targtype1_txt         0
gname                 0
individual            0
weaptype1             0
weaptype1_txt         0
property              0
dbsource              0
INT_LOG               0
INT_IDEO              0
eventid               0
dtype: int64

In [13]:
df.head()

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1,attacktype1_txt,targtype1,targtype1_txt,target1,natlty1,natlty1_txt,gname,guncertain1,individual,weaptype1,weaptype1_txt,property,ishostkid,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,1970,7,2,0,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1.0,0,1,1,1,0.0,0.0,1,0,1,Assassination,14,Private Citizens & Property,Julio Guzman,58.0,Dominican Republic,MANO-D,0.0,0,13,Unknown,0,0.0,PGIS,0,0,0,0
1,197000000002,1970,0,0,0,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,1.0,0,1,1,1,0.0,0.0,1,0,6,Hostage Taking (Kidnapping),7,Government (Diplomatic),"Nadine Chaval, daughter",21.0,Belgium,23rd of September Communist League,0.0,0,13,Unknown,0,1.0,PGIS,0,1,1,1
2,197001000001,1970,1,0,0,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4.0,0,1,1,1,0.0,0.0,1,0,1,Assassination,10,Journalists & Media,Employee,217.0,United States,Unknown,0.0,0,13,Unknown,0,0.0,PGIS,-9,-9,1,1
3,197001000002,1970,1,0,0,78,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,1.0,0,1,1,1,0.0,0.0,1,0,3,Bombing/Explosion,7,Government (Diplomatic),U.S. Embassy,217.0,United States,Unknown,0.0,0,6,Explosives,1,0.0,PGIS,-9,-9,1,1
4,197001000003,1970,1,0,0,101,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,1.0,0,1,1,1,-9.0,0.0,1,0,7,Facility/Infrastructure Attack,7,Government (Diplomatic),U.S. Consulate,217.0,United States,Unknown,0.0,0,8,Incendiary,1,0.0,PGIS,-9,-9,1,1

In [14]:
#now check the availabe columns we have
df.columns.values

array(['eventid', 'iyear', 'imonth', 'iday', 'extended', 'country',
       'country_txt', 'region', 'region_txt', 'provstate', 'city',
       'latitude', 'longitude', 'specificity', 'vicinity', 'crit1',
       'crit2', 'crit3', 'doubtterr', 'multiple', 'success', 'suicide',
       'attacktype1', 'attacktype1_txt', 'targtype1', 'targtype1_txt',
       'target1', 'natlty1', 'natlty1_txt', 'gname', 'guncertain1',
       'individual', 'weaptype1', 'weaptype1_txt', 'property',
       'ishostkid', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC',
       'INT_ANY'], dtype=object)

In [15]:
#seelcting columns to remove
to_remove = ['eventid','imonth','iday','extended','country','region','vicinity', 'crit1',
       'crit2', 'crit3', 'doubtterr', 'multiple','specificity','suicide',
       'attacktype1','targtype1','target1', 'natlty1', 'natlty1_txt', 'gname', 'guncertain1',
       'individual', 'weaptype1','property',
       'ishostkid', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC',
       'INT_ANY']

In [16]:
#removing columns which are not required
for i in df.columns:
    if(i in to_remove):
        df.drop(i,axis =1,inplace=True)

In [17]:
df.head()

,iyear,country_txt,region_txt,provstate,city,latitude,longitude,success,attacktype1_txt,targtype1_txt,weaptype1_txt
0,1970,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1,Assassination,Private Citizens & Property,Unknown
1,1970,Mexico,North America,Federal,Mexico city,19.371887,-99.086624,1,Hostage Taking (Kidnapping),Government (Diplomatic),Unknown
2,1970,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,1,Assassination,Journalists & Media,Unknown
3,1970,Greece,Western Europe,Attica,Athens,37.997490,23.762728,1,Bombing/Explosion,Government (Diplomatic),Explosives
4,1970,Japan,East Asia,Fukouka,Fukouka,33.580412,130.396361,1,Facility/Infrastructure Attack,Government (Diplomatic),Incendiary

In [19]:
#changing columns names to more readable form
df.columns = ['Year','Country','Region','Province/State','City','Latitude','Longitude','Success','Attack Type','Target Type','Weapon Type']

In [20]:
df.isna().sum()

Year                 0
Country              0
Region               0
Province/State     421
City               434
Latitude          4556
Longitude         4557
Success              0
Attack Type          0
Target Type          0
Weapon Type          0
dtype: int64

In [21]:
#filling up null values
df['City'] = df['City'].fillna('Unknown')
df['Province/State'] = df['Province/State'].fillna('Unknown')

In [22]:
df.isna().sum()

Year                 0
Country              0
Region               0
Province/State       0
City                 0
Latitude          4556
Longitude         4557
Success              0
Attack Type          0
Target Type          0
Weapon Type          0
dtype: int64

## 3. Exploring the Data

In [23]:
df.tail()

,Year,Country,Region,Province/State,City,Latitude,Longitude,Success,Attack Type,Target Type,Weapon Type
181686,2017,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,2.359673,45.385034,1,Armed Assault,Military,Firearms
181687,2017,Syria,Middle East & North Africa,Lattakia,Jableh,35.407278,35.942679,1,Bombing/Explosion,Military,Explosives
181688,2017,Philippines,Southeast Asia,Maguindanao,Kubentog,6.900742,124.437908,1,Facility/Infrastructure Attack,Private Citizens & Property,Incendiary
181689,2017,India,South Asia,Manipur,Imphal,24.798346,93.940430,0,Bombing/Explosion,Government (General),Explosives
181690,2017,Philippines,Southeast Asia,Maguindanao,Cotabato City,7.209594,124.241966,0,Bombing/Explosion,Unknown,Explosives

In [28]:
df.describe()

                Year       Latitude     Longitude        Success
count  181691.000000  177135.000000  1.771340e+05  181691.000000
mean     2002.638997      23.498343 -4.586957e+02       0.889598
std        13.259430      18.569242  2.047790e+05       0.313391
min      1970.000000     -53.154613 -8.618590e+07       0.000000
25%      1991.000000      11.510046  4.545640e+00       1.000000
50%      2009.000000      31.467463  4.324651e+01       1.000000
75%      2014.000000      34.685087  6.871033e+01       1.000000
max      2017.000000      74.633553  1.793667e+02       1.000000

In [24]:
df['Attack Type'].unique()

array(['Assassination', 'Hostage Taking (Kidnapping)',
       'Bombing/Explosion', 'Facility/Infrastructure Attack',
       'Armed Assault', 'Hijacking', 'Unknown', 'Unarmed Assault',
       'Hostage Taking (Barricade Incident)'], dtype=object)

In [25]:
df['Target Type'].unique()

array(['Private Citizens & Property', 'Government (Diplomatic)',
       'Journalists & Media', 'Police', 'Utilities', 'Military',
       'Government (General)', 'Airports & Aircraft', 'Business',
       'Educational Institution', 'Violent Political Party',
       'Religious Figures/Institutions', 'Unknown', 'Transportation',
       'Tourists', 'NGO', 'Telecommunication', 'Food or Water Supply',
       'Terrorists/Non-State Militia', 'Other', 'Maritime',
       'Abortion Related'], dtype=object)

In [26]:
df['Weapon Type'].unique()

array(['Unknown', 'Explosives', 'Incendiary', 'Firearms', 'Chemical',
       'Melee', 'Sabotage Equipment',
       'Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)',
       'Fake Weapons', 'Radiological', 'Other', 'Biological'],
      dtype=object)

## 4. Exporting cleaned data for visualization

In [27]:
df.to_csv('cleaned_data_terrorist.csv',index=False,header=True)

## Tableau viz link :
https://public.tableau.com/profile/mayankjoshi954#!/vizhome/TerroristAttacks1970-2017_16210967252220/Dashboard1